// Downloads each provider's own site icon into public/logos and writes src/data/logos.ts.
// Run: node scripts/fetch-logos.mjs   (needs network; the app itself never calls these sites)
import fs from 'node:fs';
import path from 'node:path';

// key: lower-case prefix of a provider or model name. value: the site whose icon we use, or a direct image URL.
const SITES = {
  stepfun: 'stepfun.com', alibaba: 'alibabacloud.com', microsoft: 'microsoft.com', elevenlabs: 'elevenlabs.io', spacexai: 'x.ai',
  smallest: 'smallest.ai', google: 'gemini.google.com', assemblyai: 'assemblyai.com', deepgram: 'deepgram.com', ibm: 'ibm.com',
  cohere: 'cohere.com', nvidia: 'nvidia.com', mistral: 'mistral.ai', cartesia: 'cartesia.ai', inworld: 'inworld.ai',
  speechify: 'speechify.com', 'fish audio': 'fish.audio', resemble: 'resemble.ai', hume: 'hume.ai', openai: 'openai.com',
  amazon: 'aws.amazon.com', 'ten framework': 'theten.ai', pipecat: 'pipecat.ai', livekit: 'livekit.io', krisp: 'krisp.ai',
  'ai-coustics': 'ai-coustics.com', picovoice: 'picovoice.ai', pyannoteai: 'pyannote.ai', ceva: 'ceva-ip.com',
  retell: 'retellai.com', vapi: 'vapi.ai',
  silero: 'silero.ai', hexgrad: 'https://github.com/hexgrad.png', 'but (': 'https://github.com/BUTSpeechFIT.png',
};
const UA = { 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/126 Safari/537.36' };
const get = (u) => fetch(u, { headers: UA, redirect: 'follow', signal: AbortSignal.timeout(12000) });

function candidates(html, base) {
  const out = [];
  for (const tag of html.match(/<link\b[^>]*>/gi) ?? []) {
    const rel = /rel=["']([^"']+)["']/i.exec(tag)?.[1]?.toLowerCase() ?? '';
    const href = /href=["']([^"']+)["']/i.exec(tag)?.[1];
    if (!href || !rel.includes('icon')) continue;
    const sizes = /sizes=["'](\d+)x\d+["']/i.exec(tag)?.[1];
    const svg = /image\/svg/i.test(tag) || /\.svg(\?|$)/i.test(href);
    const apple = rel.includes('apple');
    let url; try { url = new URL(href, base).href; } catch { continue; }
    out.push({ url, score: (svg ? 1000 : 0) + (apple ? 400 : 0) + (sizes ? +sizes : 32) });
  }
  return out.sort((a, b) => b.score - a.score).map((c) => c.url);
}

async function grab(domain) {
  let urls = [];
  if (domain.startsWith('http')) urls = [domain];
  else try { const r = await get(`https://${domain}`); urls = candidates(await r.text(), r.url); } catch {}
  if (!domain.startsWith('http')) urls.push(`https://${domain}/apple-touch-icon.png`, `https://${domain}/favicon.ico`, `https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://${domain}&size=128`);
  for (const u of urls) {
    try {
      const r = await get(u);
      if (!r.ok) continue;
      const type = r.headers.get('content-type') ?? '';
      const buf = Buffer.from(await r.arrayBuffer());
      if (buf.length < 200 || /text\/html/.test(type)) continue;
      const head = buf.subarray(0, 80).toString('latin1');
      const ext = /^\s*<(\?xml|svg)/.test(head) ? 'svg' : buf[0] === 0x89 ? 'png' : buf[0] === 0xff ? 'jpg' : buf[2] === 1 && buf[0] === 0 ? 'ico' : head.startsWith('RIFF') ? 'webp' : null;
      if (!ext) continue;
      return { buf, ext, from: u };
    } catch {}
  }
  return null;
}

fs.mkdirSync('public/logos', { recursive: true });
const done = {};
await Promise.all(Object.entries(SITES).map(async ([key, domain]) => {
  const g = await grab(domain);
  if (!g) { console.log('MISS', key, domain); return; }
  const file = `${key.replace(/[^a-z0-9]+/g, '-')}.${g.ext}`;
  fs.writeFileSync(path.join('public/logos', file), g.buf);
  done[key] = file;
  console.log('ok  ', key.padEnd(14), g.ext, g.buf.length, g.from.slice(0, 90));
}));
const body = Object.entries(done).sort().map(([k, f]) => `  '${k}': '${f}',`).join('\n');
fs.writeFileSync('src/data/logos.ts', `// Generated by scripts/fetch-logos.mjs. Key is a lower-case prefix of a provider or model name.\nexport const LOGOS: Record<string, string> = {\n${body}\n};\n`);
